### PR TITLE
fix: connector jar was replacing the folder name instead of getting added as a content inside the folder

### PR DESCRIPTION
**Pull request by kavinrites**
The connector jar was not placed inside the folder connectors/

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jhughes24816 — APPROVED** [review]
LGTM

**Comment by tekipanda** [comment]
> Before I can merge this could you please read through the [contributing.md](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/CONTRIBUTING.md) and edit your commit message to sign off correctly. Thanks

Thanks for reviewing modified the commit message and added Sign Off

**Comment by david-VigneshN** [comment]
Quick question:

Why did we move the mq source connector jar to /opt/connectors/ instead of /opt/kafka/libs/ ??

`COPY --chown=esuser:esgroup target/kafka-connect-*-jar-with-dependencies.jar /opt/connectors/`

if i use this in my docker image i get a class not found exception for MQ source connector in kafka connect.

**Comment by Joel-hanson** [comment]
Closing this as we already have this change.

**Pull request closed without merging**
