### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by Celebrate-future**
@katheris Hi, I am a user of project **_com.ibm.eventstreams.connect:kafka-connect-mq-source:1.3.1_**. I found that its pom file introduced **_26_** dependencies. However, among them, **_8_** libraries (**_30%_**) have not been used by your project (the redundant dependencies are listed below). This PR helps **_com.ibm.eventstreams.connect:kafka-connect-mq-source:1.3.1_** lose weight :) I have tested the revised configuration in my local environment. It is safe to remove the unused libraries.

Best regards

## Redundant dependencies----
<pre><code>
org.json:json:jar:20080701:compile
net.bytebuddy:byte-buddy-agent:jar:1.9.10:test
org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
com.fasterxml.jackson.core:jackson-core:jar:2.10.2:provided
org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
com.fasterxml.jackson.core:jackson-annotations:jar:2.10.2:provided
com.fasterxml.jackson.core:jackson-databind:jar:2.10.2:provided
com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.2:provided
</code></pre>

### CODE REVIEW

**Comment by slachiewicz** [comment]
Could You correct the new line encodings?

**Comment by Celebrate-future** [comment]
> Could You correct the new line encodings?

Ok, I will create a new PR.

**Comment by Celebrate-future** [comment]
> > Could You correct the new line encodings?
> 
> Ok, I will create a new PR.

The Link of new PR is https://github.com/ibm-messaging/kafka-connect-mq-source/pull/86

**Comment by AndrewJSchofield** [comment]
Hi, thanks for the PR.

In your configuration, I think it's OK to remove the dependencies. However, in the general case, I don't think so. There are configurations I'm sure in which the removed dependencies would be used. So, I am going to close the pull request and encourage you to build your own version for your use with the dependencies you identified excluded.

**Pull request closed without merging**
