### PR TITLE
fix: close JMS reader when connect task is stopped

### PR DESCRIPTION
**Pull request by dalelane**
Closes: #73

### CODE REVIEW

**Comment by dalelane** [comment]
This is a copy of the pull request #76 with the following changes:
- rebased with the current `master` branch
- updated to fix the tests broken by this change

**Comment by dalelane** [comment]
This is a copy of the pull request #76 with the following changes (each in separate commits):
- rebased with the current `master` branch
- updated existing tests broken by this change in behaviour
- added a new test that covers this new change

**Comment by jhughes24816** [comment]
@khetanshu We would like to contribute your fix, for which @dalelane has kindly adjusted the tests. Since you contributed the original commit please could you follow the instructions here https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/CONTRIBUTING.md to give us permission to use your contribution. Many thanks 👍

**Comment by khetanshu** [comment]
Sure @jhughes24816.  Can you please help me know what I can do to grant you permission?

**Comment by jhughes24816** [comment]
Brill thanks @khetanshu Please read through https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/CONTRIBUTING.md.
If you are happy with this then please could you create a new branch with your changes and a single commit with the `Signed-off-by` line at the end of the commit message.
Screenshot 2022-12-12 at 14 07 20

**Comment by khetanshu** [comment]
@jhughes24816  I have comment the signed-off statement in my [original commit](https://github.com/khetanshu/kafka-connect-mq-source/commit/1ee5c05844f3e3f40e398e61cb6acaac3a5e3cd7), would that work ?

**Comment by jhughes24816** [comment]
@khetanshu technically this does not meet the requirement. I have put together a set of instructions (from [here]( https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message)) to help:
1. On your fork checkout the branch you created for this pull request https://github.com/khetanshu/kafka-connect-mq-source/tree/fixed_issue_73_jms_open_conn
2. Then you can use 
```
git commit --amend -m "<New-message>"
```
 to change the commit message. 
Make sure to include `Signed-off-by: Khetanshu Chauhan [khetanshu.chauhan@gmail.com](mailto:khetanshu.chauhan@gmail.com)` in the new message.
3. Push the new commit message using
```
git push --force
```
4. Create a new pull request to the https://github.com/ibm-messaging/kafka-connect-mq-source main branch and we can handle the rest from there.

If you face any further issues just get in touch and I can help you out. Many thanks and Happy Christmas!

**Comment by khetanshu** [comment]
@jhughes24816 Thank you! I have amended (with sign) and pushed.

**Review by gmcrobert — APPROVED** [review]

**Pull request merged**
